"""pending_changes.edited_at

Revision ID: e722e2638ce1
Revises: c416b77fadf6
Create Date: 2026-07-29 00:12:59.876688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e722e2638ce1'
down_revision: Union[str, Sequence[str], None] = 'c416b77fadf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_changes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_changes', schema=None) as batch_op:
        batch_op.drop_column('edited_at')

    # ### end Alembic commands ###
